### ISSUE TITLE
Minecart Map

### ISSUE THREAD

**Issue by elwakka** [MJHylkema/spirit-tree-map#14]
New update has been out for like 2 hours already.  When minecart map?

**Comment by MJHylkema** [comment]
![image-1](https://github.com/MJHylkema/spirit-tree-map/assets/20365453/00cb4d95-c420-41bd-9332-03f0f2558f12)
🥸

**Comment by elwakka** [comment]
About time.  Yeesh.  My cloths already went out of style.

It's a good start, but I added a little bit to the map to help it really pop.

And best of all, it was brought to you buy todays sponsor:

![295798771-00cb4d95-c420-41bd-9332-03f0f2558f12 (1)](https://github.com/MJHylkema/spirit-tree-map/assets/67753396/25fb6f97-82e5-4497-b670-55ae4c9d1269)
