### ISSUE TITLE
Lovakengj minecart system would also work for this

### ISSUE THREAD

**Issue by Mysterybug009** [MJHylkema/spirit-tree-map#20]
hey the lovakengj minecart system would work to have one of these graphics teleport menus, especially considering you can ride them anytime for small charge or free after quests, because they have removed kourend favour.

**Comment by MJHylkema** [comment]
Already implemented, just waiting on it to be approved 👍🏼 

See: https://github.com/runelite/plugin-hub/pull/5397

**Comment by MJHylkema** [comment]
Minecart map is now live 👍
