### ISSUE TITLE
FEATURE REQUEST - Xerics Talisman? 

### ISSUE THREAD

**Issue by santzuu** [MJHylkema/spirit-tree-map#21]
HI! I saw that you already answered to the request about the minecarft system (absolutely fantastic btw and was going to request/inquire about that as well on this one :P) 

I was wondering also if you have on the plan/if its possible to add also the xerixs talisman to this list? That doesnt have too many teleport options and would be neat to have! Absolutely fantastic work on the 2 teleport maps already and cant wait for the minecart system and if you get the fairy rings as well! Massive cheers!

**Comment by MJHylkema** [comment]
I have also implemented Xerics Talisman, it is included in the same pull request as the minecart map. Still just waiting on some lovely person to approve it. ☺️

![297062419-3ad3a62b-ac22-4efb-9f26-2fffbb650dec](https://github.com/MJHylkema/spirit-tree-map/assets/20365453/19504380-251a-40b4-b163-8c55e13d259c)

Pull request: https://github.com/runelite/plugin-hub/pull/5397

**Comment by MJHylkema** [comment]
Xerics Talisman is now live 👍
