### ISSUE TITLE
Cant teleport with Xeric's talisman

### ISSUE THREAD

**Issue by Tooloco** [MJHylkema/spirit-tree-map#24]
I only get the option to examine the tp locations and the msg: "The talisman does not have the poiwer to take you to <tp location> yet." 
If I disable the plugin I can teleport correctly

**Comment by MJHylkema** [comment]
Thanks for reporting. I have fixed this issue in #23, just waiting for a runelite dev to approve the plugin hub pull request. 

As mentioned in #22, you can just turn off the Xerics Map for the Teleport Maps plugin until my patch is merged.

![image](https://github.com/MJHylkema/spirit-tree-map/assets/20365453/f687a2d0-8ca5-4f47-a40e-39d7c6a76495)

**Comment by Tooloco** [comment]
Thank you for speedy response.

**Comment by MJHylkema** [comment]
No worries. Hopefully it will be merged promptly. 👍

duplicate of #22

**Comment by MJHylkema** [comment]
Fix is now live, restarting client should solve the issue.
