### ISSUE TITLE
Spirit Tree Map not working

### ISSUE THREAD

**Issue by blubaru14** [MJHylkema/spirit-tree-map#37]
![image](https://github.com/user-attachments/assets/2049c035-23a2-4626-a2a8-c399aafeda59)

If i click on a spirit tree icon, the chat window says: The Spirit Tree at [location] is not available. If i turn the plugin off, I can use the teleports just fine via the stock teleport list.

![image](https://github.com/user-attachments/assets/516bbfce-418b-41db-a04f-960441e97489)

**Comment by MJHylkema** [comment]
Unfortunately this plugin is incompatible with [Spirit Tree Menu](https://runelite.net/plugin-hub/show/spirit-tree-menu). I suggest you turn off Spirit Tree Menu while using Teleport Maps, as it will replace the menu anyway.
