### ISSUE TITLE
Request: Add Xerics Talisman Map

### ISSUE THREAD

**Issue by Durpiee** [MJHylkema/spirit-tree-map#7]
I was wondering if it would possible to add in a teleport map for the Xerics Talisman? :D

**Comment by MJHylkema** [comment]
Absolute! Myself and NinjaPig have already started working on this one. Here is a preview

![image](https://github.com/MJHylkema/spirit-tree-map/assets/20365453/85dc1b70-0ce3-46cd-b559-dad7094304d3)

**Comment by Durpiee** [comment]
Fuck thats hot , keep on soldiering! :D Ill wait patiently.
